name: Build

on:
  workflow_call:
    inputs:
      version_code:
        required: true
        type: string
  pull_request:
    branches: ["dev", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - uses: ./.github/workflows/actions/create-version-props
        with:
          version_code: ${{ inputs.version_code || vars.VERSION_CODE }}

      - name: Build APK
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]] || [[ "${{ github.base_ref }}" == "main" ]]; then
            ./gradlew assembleRelease
          else
            ./gradlew assembleDebug
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref == 'refs/tags/*' && 'release' || 'debug' }}-apk
          path: app/build/outputs/apk/**/*.apk