name: Build

on:
  workflow_call:
    inputs:
      version_code:
        required: true
        type: string
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - uses: ./.github/workflows/actions/create-version-props
        with:
          version_code: ${{ inputs.version_code || vars.VERSION_CODE }}

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Rename APK
        run: |
          WORKSPACE_DIR=$(pwd)
          VERSION_NAME=$(cat version.properties | grep "VERSION_NAME" | cut -d'=' -f2)
          APP_ID=$(./gradlew -q printApplicationId | tail -n 1)
          cd app/build/outputs/apk/debug
          mv app-debug.apk "${APP_ID}-${VERSION_NAME}-debug.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*-debug.apk