name: CI/CD

on:
  pull_request:
    branches: [ "main", "dev" ]
  pull_request_target:
    types: [closed]
    branches: ["dev"]
  push:
    branches: ["main"]
    tags:
      - 'v*'

# PR이 머지되기 전에 모든 체크가 통과되어야 함을 명시
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 코드 검증 작업
  validate:
    if: |
      github.event_name == 'pull_request' && 
      !github.event.pull_request.merged
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Check code style
        run: ./gradlew spotlessCheck
        
      - name: Run Android Lint
        run: ./gradlew lint
        
      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

  # 테스트 및 빌드 작업 (통합)
  test-and-build:
    name: Test and Build
    needs: [validate]
    if: |
      github.event_name == 'pull_request' && 
      !github.event.pull_request.merged
    runs-on: ubuntu-latest
    outputs:
      apk_path: ${{ steps.build-apk.outputs.apk_path }}
      build_type: ${{ steps.set-build-type.outputs.build_type }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
        
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/reports/tests/testDebugUnitTest/

      # 빌드 타입 설정
      - name: Set Build Type
        id: set-build-type
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "build_type=release" >> $GITHUB_OUTPUT
          else
            echo "build_type=debug" >> $GITHUB_OUTPUT
          fi

      # APK 빌드 (PR 검증 또는 배포용)
      - name: Build APK
        id: build-apk
        run: |
          if [[ "${{ steps.set-build-type.outputs.build_type }}" == "release" ]]; then
            ./gradlew assembleRelease
            APK_DIR="app/build/outputs/apk/release"
            APK_PATTERN="*-release-unsigned.apk"
          else
            ./gradlew assembleDebug
            APK_DIR="app/build/outputs/apk/debug"
            APK_PATTERN="*-debug.apk"
          fi
          
          # APK 파일 찾기
          APK_FILE=$(find "$APK_DIR" -name "$APK_PATTERN" -type f)
          if [ ! -z "$APK_FILE" ]; then
            echo "APK built successfully at: $APK_FILE"
            echo "apk_path=$APK_FILE" >> $GITHUB_OUTPUT
          else
            echo "Error: APK not found matching pattern: $APK_PATTERN"
            echo "Listing contents of $APK_DIR/:"
            ls -la "$APK_DIR"
            exit 1
          fi

      # 빌드 결과물 저장
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            app/build/outputs/apk/
            version.properties
          retention-days: 1

  # 버전 관리 작업 (릴리즈 시에만)
  version-management:
    name: Version Management
    if: |
      github.event_name == 'pull_request_target' && 
      github.event.pull_request.merged == true && 
      github.base_ref == 'dev'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    outputs:
      version_code: ${{ steps.version-update.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Version Code
        id: version-update
        uses: actions/github-script@v7
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            const currentVersion = parseInt('${{ vars.VERSION_CODE }}') || 0;
            const newVersion = currentVersion + 1;
            
            await github.rest.actions.updateRepoVariable({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'VERSION_CODE',
              value: newVersion.toString()
            });
            
            console.log(`Version Code updated: ${currentVersion} → ${newVersion}`);
            core.setOutput('new_version', newVersion.toString());

      - name: Create Version Tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          timestamp=$(date +%Y%m%d%H%M%S)
          latest_tag=$(git tag -l "v*" | grep -v "beta" | sort -V | tail -n 1)
          
          if [ -z "$latest_tag" ]; then
            base_version="1.0.0"
          else
            base_version=$(echo $latest_tag | sed 's/^v//')
            IFS='.' read -r major minor patch <<< "$base_version"
            
            case "${{ github.head_ref }}" in
              major/*)
                base_version="$((major + 1)).0.0"
                ;;
              feat/*)
                base_version="$major.$((minor + 1)).0"
                ;;
              fix/* | *)
                base_version="$major.$minor.$((patch + 1))"
                ;;
            esac
          fi
          
          new_version="v${base_version}-beta.$timestamp"
          echo "Creating beta tag: $new_version"
          git tag -a "$new_version" -m "Beta release $new_version"
          git push origin "$new_version"

  # 배포 작업
  deploy:
    name: Deploy APK
    needs: [test-and-build, version-management]
    if: |
      (github.event_name == 'pull_request_target' && 
       github.event.pull_request.merged == true && 
       github.base_ref == 'dev') ||
      (github.event_name == 'push' && 
       startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        
      # 빌드 결과물 다운로드
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .

      # 릴리즈 노트 생성 (태그 푸시 시에만)
      - name: Generate Release Notes
        if: startsWith(github.ref, 'refs/tags/v')
        id: release_notes
        run: |
          version=$(git describe --tags --abbrev=0)
          previous_tag=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          echo "## 변경 사항" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "버전: $version" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          
          if [ -z "$previous_tag" ]; then
            git log --pretty=format:"- %s" >> CHANGELOG.md
          else
            git log --pretty=format:"- %s" ${previous_tag}..HEAD >> CHANGELOG.md
          fi

      # GitHub 릴리즈 생성 (태그 푸시 시에만)
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/apk/release/*-release-unsigned.apk
          name: "v${{ vars.VERSION_MAJOR }}.${{ vars.VERSION_MINOR }}.${{ vars.VERSION_PATCH }}"
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 