name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'  # main 브랜치의 태그만 감지

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - uses: ./.github/workflows/actions/create-version-props
        with:
          version_code: ${{ vars.VERSION_CODE }}

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Generate Release Notes
        id: release_notes
        run: |
          version=$(git describe --tags --abbrev=0)
          previous_tag=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          echo "## 변경 사항" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "버전: $version" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          
          if [ -z "$previous_tag" ]; then
            git log --pretty=format:"- %s" >> CHANGELOG.md
          else
            git log --pretty=format:"- %s" ${previous_tag}..HEAD >> CHANGELOG.md
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/apk/release/app-release-unsigned.apk
          name: "v${{ vars.VERSION_MAJOR }}.${{ vars.VERSION_MINOR }}.${{ vars.VERSION_PATCH }}"
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}